"""Regenerate small, deterministic font subsets and profile image sizes.

Run after adding icons to templates or replacing images/profile_dez.jpg.
Install scripts/requirements-assets.txt in a virtual environment first.
Original fonts, licenses, and the original photograph remain unchanged.
"""
from pathlib import Path
import re

from fontTools import subset
from fontTools.ttLib import TTFont
from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parents[1]


def build_fonts():
    sources = []
    for directory in ('_includes', '_layouts', '_pages', '_publications', '_data', 'assets/js'):
        for path in (ROOT / directory).rglob('*'):
            if path.suffix in ('.html', '.md', '.js', '.yml', '.json') and not path.name.endswith('.min.js'):
                sources.append(path.read_text())
    text = '\n'.join(sources)
    wanted_fa = set(re.findall(r'\bfa-([a-z0-9-]+)', text))
    wanted_ai = set(re.findall(r'\bai-([a-z0-9-]+)', text))
    fa = dict(re.findall(r'\$fa-var-([\w-]+):\s*\\([0-9a-f]+);',
                         (ROOT / '_sass/vendor/font-awesome/_variables.scss').read_text()))
    ai = dict(re.findall(r'\.ai-([\w-]+):before\s*\{\s*content:\s*"\\([0-9a-f]+)";',
                         (ROOT / 'assets/css/academicons.css').read_text()))
    css = ['/*! Generated by scripts/optimize_assets.py. Font Awesome 6.5.2: Fonticons, Inc.; fonts SIL OFL 1.1, code MIT. Academicons 1.9.4: James Walsh and Katja Bercic; fonts SIL OFL 1.1, CSS MIT. */']
    for source, output, family, weight, mapping, wanted in [
        ('assets/webfonts/fa-solid-900.woff2', 'site-solid.woff2', 'Font Awesome 6 Free', 900, fa, wanted_fa),
        ('assets/webfonts/fa-brands-400.woff2', 'site-brands.woff2', 'Font Awesome 6 Brands', 400, fa, wanted_fa),
        ('assets/fonts/academicons.ttf', 'site-academicons.woff2', 'Academicons', 400, ai, wanted_ai),
    ]:
        font = TTFont(ROOT / source, recalcTimestamp=False)
        codepoints = {int(mapping[name], 16) for name in wanted if name in mapping}
        codepoints &= set(font.getBestCmap())
        options = subset.Options()
        options.flavor = 'woff2'
        subsetter = subset.Subsetter(options=options)
        subsetter.populate(unicodes=codepoints)
        subsetter.subset(font)
        font.flavor = 'woff2'
        font.save(ROOT / 'assets/webfonts' / output)
        css.append(f"@font-face {{ font-family: '{family}'; font-style: normal; font-weight: {weight}; font-display: swap; src: url('../webfonts/{output}') format('woff2'); }}")
        print(f'{output}: {len(codepoints)} glyphs, {(ROOT / "assets/webfonts" / output).stat().st_size:,} bytes')
    css += [
        '.fas, .fa-solid { font-weight: 900; }',
        '.fab, .fa-brands { font-weight: 400; }',
        ".ai { font-family: 'Academicons'; font-weight: 400; display: inline-block; font-style: normal; line-height: 1; -webkit-font-smoothing: antialiased; }",
        '.ai-fw { width: 1.25em; text-align: center; }',
    ]
    for prefix, mapping, wanted in [('fa', fa, wanted_fa), ('ai', ai, wanted_ai)]:
        for name in sorted(wanted & mapping.keys()):
            css.append(f'.{prefix}-{name}::before {{ content: "\\{mapping[name]}"; }}')
    (ROOT / '_sass/_site-icons.scss').write_text('\n'.join(css) + '\n')


def build_photos():
    with Image.open(ROOT / 'images/profile_dez.jpg') as source:
        image = ImageOps.exif_transpose(source).convert('RGB')
        for width in (80, 350):
            height = round(image.height * width / image.width)
            output = ROOT / f'images/profile-{width}.webp'
            image.resize((width, height), Image.Resampling.LANCZOS).save(output, quality=82, method=6)
            print(f'{output.name}: {width}x{height}, {output.stat().st_size:,} bytes')


if __name__ == '__main__':
    build_fonts()
    build_photos()
